[package]
name = "p3-matrix"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field" }
p3-maybe-rayon = { path = "../maybe-rayon" }
rand = "0.8.5"
