[package]
name = "p3-keccak"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-symmetric = { path = "../symmetric" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
