[package]
name = "p3-reed-solomon"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-code = { path = "../code" }
p3-field = { path = "../field" }
p3-lde = { path = "../lde" }
p3-matrix = { path = "../matrix" }
