[package]
name = "p3-challenger"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field" }
p3-symmetric = { path = "../symmetric" }

[dev-dependencies]
p3-goldilocks = { path = "../goldilocks" }
